import type { WebNode } from '@src/web/ui-schema';

import type { NrAuthorGroup } from '../../shared/types';

import { authorsSectionNode } from './authors';
import { sectionNode, type ListModeNodesProps } from './event-nodes';

type TimelineNodesProps = ListModeNodesProps & {
  authorGroups: NrAuthorGroup[];
};

export function timelineNodes(props: TimelineNodesProps): WebNode[] {
  const {
    alias,
    topicGroups,
    moodGroups,
    languageGroups,
    profiles,
    interactions,
    localPreferences,
    authorPreferences,
    sharePrefixes,
    translationTargetLanguage,
    rankingScores,
    archiveSignalReviewMode,
    likeSignalReviewMode,
    replySignalReviewMode,
    repostQuoteSignalReviewMode,
    resolveReferencesAutomatically,
    mode,
    selectedTimeRanges,
    archivedIds,
    evaluatedImageCounts,
    followedPubkeys,
    conversationContextEvents,
  } = props;

  return [
    sectionNode({
      alias,
      title: 'Topics',
      type: 'topic',
      groups: topicGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
      archivedIds,
      evaluatedImageCounts,
      followedPubkeys,
      conversationContextEvents,
    }),
    sectionNode({
      alias,
      title: 'Moods',
      type: 'mood',
      groups: moodGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
      archivedIds,
      evaluatedImageCounts,
      followedPubkeys,
      conversationContextEvents,
    }),
    sectionNode({
      alias,
      title: 'Languages',
      type: 'language',
      groups: languageGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
      archivedIds,
      evaluatedImageCounts,
      followedPubkeys,
      conversationContextEvents,
    }),
    authorsSectionNode(props),
  ];
}
