import type { WebNode } from '@src/web/ui-schema';

import { sectionNode, type ListModeNodesProps } from './event-nodes';

export function timelineNodes({
  alias,
  topicGroups,
  moodGroups,
  languageGroups,
  profiles,
  interactions,
  localPreferences,
  authorPreferences,
  sharePrefixes,
  translationTargetLanguage,
  rankingScores,
  archiveSignalReviewMode,
  likeSignalReviewMode,
  replySignalReviewMode,
  repostQuoteSignalReviewMode,
  resolveReferencesAutomatically,
  mode,
  selectedTimeRanges,
}: ListModeNodesProps): WebNode[] {
  return [
    sectionNode({
      alias,
      title: 'Topics',
      type: 'topic',
      groups: topicGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
    }),
    sectionNode({
      alias,
      title: 'Moods',
      type: 'mood',
      groups: moodGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
    }),
    sectionNode({
      alias,
      title: 'Languages',
      type: 'language',
      groups: languageGroups,
      profiles,
      interactions,
      localPreferences,
      authorPreferences,
      sharePrefixes,
      translationTargetLanguage,
      rankingScores,
      archiveSignalReviewMode,
      likeSignalReviewMode,
      replySignalReviewMode,
      repostQuoteSignalReviewMode,
      resolveReferencesAutomatically,
      mode,
      selectedTimeRanges,
    }),
  ];
}
