import type { SubcommandDefinition } from '@src/system/command-definition';

import { DEFAULT_NR_CLASSIFICATION_INSTRUCTIONS } from '../../settings';

export const settingsDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'settings',
  summary: 'Show or update NR evaluation mode and classifier settings.',
  aliases: ['config'],
  arguments: [],
  options: [
    {
      name: 'mode',
      flag: '--mode',
      summary: 'Evaluation mode (LLM or System One classifier).',
      kind: 'string',
      required: false,
      choices: ['llm', 'classifier'],
    },
    {
      name: 'jev_topics',
      flag: '--jev-topics',
      summary: 'Comma-separated candidate topics.',
      kind: 'string',
      required: false,
    },
    {
      name: 'jev_topic_batch_size',
      flag: '--jev-topic-batch-size',
      summary: 'Choices per topic or mood question (1-50, default 10).',
      kind: 'integer',
      required: false,
    },
    {
      name: 'jev_moods',
      flag: '--jev-moods',
      summary: 'Comma-separated candidate moods.',
      kind: 'string',
      required: false,
    },
    {
      name: 'jev_languages',
      flag: '--jev-languages',
      summary: 'Comma-separated ISO 639-1 language codes.',
      kind: 'string',
      required: false,
    },
    {
      name: 'jev_state_instructions',
      flag: '--jev-state-instructions',
      summary: 'State guidance for Jev.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
    },
    {
      name: 'jev_topic_question',
      flag: '--jev-topic-question',
      summary: 'Jev topic question.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
    },
    {
      name: 'jev_mood_question',
      flag: '--jev-mood-question',
      summary: 'Jev mood question.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
    },
    {
      name: 'jev_language_question',
      flag: '--jev-language-question',
      summary: 'Jev language question.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
    },
    {
      name: 'jev_relevance_question',
      flag: '--jev-relevance-question',
      summary: 'Jev relevance question.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
    },
    {
      name: 'backend',
      flag: '--backend',
      summary: 'Backend for nr parse AI classification.',
      kind: 'string',
      required: false,
      choices: ['opencode'],
    },
    {
      name: 'model',
      flag: '--model',
      summary: 'Model override for nr parse AI classification.',
      kind: 'string',
      required: false,
    },
    {
      name: 'image_backend',
      flag: '--image-backend',
      summary: 'Backend override for image evaluation.',
      kind: 'string',
      required: false,
      choices: ['opencode'],
    },
    {
      name: 'image_model',
      flag: '--image-model',
      summary: 'Model override for image evaluation.',
      kind: 'string',
      required: false,
    },
    {
      name: 'agent',
      flag: '--agent',
      summary: 'Open the backend and model settings dialog.',
      kind: 'boolean',
      required: false,
    },
    {
      name: 'instructions',
      flag: '--instructions',
      summary: 'Classification instructions for nr parse.',
      kind: 'string',
      required: false,
      webInput: 'textarea',
      webDefaultValue: DEFAULT_NR_CLASSIFICATION_INSTRUCTIONS,
    },
    {
      name: 'reset',
      flag: '--reset',
      summary: 'Clear text AI, image AI, and instructions overrides.',
      kind: 'boolean',
      required: false,
    },
    {
      name: 'event_share_prefix',
      flag: '--event-share-prefix',
      summary: 'Event share URL prefix or template containing [nevent].',
      kind: 'string',
      required: false,
    },
    {
      name: 'profile_share_prefix',
      flag: '--profile-share-prefix',
      summary: 'Profile share URL prefix or template containing [nprofile].',
      kind: 'string',
      required: false,
    },
    {
      name: 'default_language',
      flag: '--default-language',
      summary:
        'BCP 47 language omitted from timeline language groups (default: en).',
      kind: 'string',
      required: false,
    },
    {
      name: 'translation_target_language',
      flag: '--translation-target-language',
      summary: 'BCP 47 target language for post translation (default: en).',
      kind: 'string',
      required: false,
    },
    {
      name: 'hourly_scheduler',
      flag: '--hourly-scheduler',
      summary: 'Create an hourly scheduler to fetch and evaluate Nostr posts.',
      kind: 'boolean',
      required: false,
    },
    {
      name: 'filter_to_latest_fetched_slot_on_open',
      flag: '--filter-to-latest-fetched-slot-on-open',
      summary:
        'Select the latest fetched or partially fetched hour when Nostr Radar first opens.',
      kind: 'string',
      required: false,
      choices: ['enabled', 'disabled'],
    },
    {
      name: 'always_resolve_unresolved_references',
      flag: '--always-resolve-unresolved-references',
      summary: 'Automatically load unresolved referenced posts.',
      kind: 'string',
      required: false,
      choices: ['enabled', 'disabled'],
    },
    {
      name: 'relay_fetch_concurrency',
      flag: '--relay-fetch-concurrency',
      summary: 'Maximum relay-author groups fetched concurrently.',
      kind: 'integer',
      required: false,
    },
    {
      name: 'ai_evaluation_concurrency',
      flag: '--ai-evaluation-concurrency',
      summary: 'Maximum AI evaluations run concurrently.',
      kind: 'integer',
      required: false,
    },
    {
      name: 'evaluate_images',
      flag: '--evaluate-images',
      summary: 'Evaluate attached images with AI vision.',
      kind: 'string',
      required: false,
      choices: ['enabled', 'disabled'],
    },
    {
      name: 'max_images_per_event',
      flag: '--max-images-per-event',
      summary: 'Maximum images evaluated per event.',
      kind: 'integer',
      required: false,
    },
    {
      name: 'max_image_mb',
      flag: '--max-image-mb',
      summary: 'Maximum image size in MB.',
      kind: 'integer',
      required: false,
    },
    {
      name: 'image_fetch_timeout_sec',
      flag: '--image-fetch-timeout-sec',
      summary: 'Timeout in seconds for each image fetch.',
      kind: 'integer',
      required: false,
    },
    {
      name: 'archive_signal_review_mode',
      flag: '--archive-signal-review-mode',
      summary: 'Signal review behavior for archive actions.',
      kind: 'string',
      required: false,
      choices: ['ask', 'always', 'never'],
    },
    {
      name: 'like_signal_review_mode',
      flag: '--like-signal-review-mode',
      summary: 'Signal review behavior for public likes.',
      kind: 'string',
      required: false,
      choices: ['ask', 'always', 'never'],
    },
    {
      name: 'reply_signal_review_mode',
      flag: '--reply-signal-review-mode',
      summary: 'Signal review behavior for replies.',
      kind: 'string',
      required: false,
      choices: ['ask', 'always', 'never'],
    },
    {
      name: 'repost_quote_signal_review_mode',
      flag: '--repost-quote-signal-review-mode',
      summary: 'Signal review behavior for reposts and quotes.',
      kind: 'string',
      required: false,
      choices: ['ask', 'always', 'never'],
    },
  ],
  examples: [
    `${prefix}${alias} settings`,
    `${prefix}${alias} settings --backend opencode --model openrouter/google/gemini-2.0-flash-exp:free`,
    `${prefix}${alias} settings --reset`,
  ],
});
